### ISSUE TITLE
zooming in remote pdf

### ISSUE THREAD

**Issue by shyamsam** [voghDev/PdfViewPager#8] opened 2016-06-09 06:47 UTC
I have integrate your library in my app. But am facing an issue when am populating the downloaded pdf from remote server. The issue is that the pdf is not zoomable. 

Part of the xml is : 

         <es.voghdev.pdfviewpager.library.PDFViewPagerZoom
            android:id="@+id/pdfViewPager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1.55"
          />

Am able to download and view the pdf in the activity. The portion of the code is given below:

    public class Pdf extends AppCompatActivity implements DownloadFile.Listener{
      RemotePDFViewPager remotePDFViewPager;
     PDFPagerAdapter adapter;
       PDFViewPager pdfViewPager;

     @Override
    public void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
    remotePDFViewPager = new RemotePDFViewPager(getBaseContext(), "http://partners.adobe.com/public/developer/en/xml/AdobeXMLFormsSamples.pdf",this);
               pdfViewPager = (PDFViewPager) findViewById(R.id.pdfViewPager);
    }

    public static void open(Context context){
        Intent i = new Intent(context, Pdf.class);
        context.startActivity(i);
    }

      @Override
        public void onSuccess(String url, String destinationPath) {
      
        adapter = new PDFPagerAdapter(this, FileUtil.extractFileNameFromURL(url));
         pdfViewPager.setAdapter(adapter);
     }

In onSucces if am using PDFPagerAdapterZoom , the pdf which gets loaded to activity is so small, then too am able to zoom it. But I want the pdf to be as the size when I use PDFPagerAdapter and with zooming option in it. 
How to make pdf as the size of when it loads via PDFPagerAdapter with zooming ?

**Comment by voghDev** [comment] 2016-06-09 10:14
Hello,

If I haven't understood you wrong, you want to set up an initial zoom level in the PDF document, then be able to zoom/unzoom it.

The issue is similar to [this other](https://github.com/voghDev/PdfViewPager/issues/3). I'm trying to implement an elegant default zooming solution, but haven't found the best one yet.

I suggest you to do what the user does,

    pdfViewPager.setScaleX(1.5f);

**Comment by shyamsam** [comment] 2016-06-09 10:23
When I give 
pdfViewPager.setScaleX(1.5f);
I finding that the ui is not looking good.
If is give pdfViewPager.setScaleY(1.5f);
I could see that some portion of pdf am not able to see. Is there any solution for the same ?

**Comment by voghDev** [comment] 2016-06-16 15:21
Hello,


yes, you can do that. Just download the PDF file and assign it a zooming pager adapter when download is complete.


Have a look at the samples, I think one of the remote ones is zoomable.


Just use the zoomable adapter.


Let me know if it helps :)


Thanks for using the lib



________________________________
De: shyamsam <notifications@github.com>
Enviado: jueves, 9 de junio de 2016 8:47
Para: voghDev/PdfViewPager
Asunto: [voghDev/PdfViewPager] zooming in remote pdf (#8)


May I know what are changes to be done when am downloading a pdf from a remote server. As per your sample it shows the pdf in the actvity, but is it possible to make that pdf zoomable ?

-

**Comment by voghDev** [comment] 2016-06-16 15:23
In next releases of the lib I'm planning to set a default zoom level. It is not done yet.


You can check changes in the make_scale_setable branch.


Thx for using the lib! Hope you like it


________________________________
De: shyamsam <notifications@github.com>
Enviado: jueves, 9 de junio de 2016 12:23
Para: voghDev/PdfViewPager
Cc: Olmo Gallegos; Comment
Asunto: Re: [voghDev/PdfViewPager] zooming in remote pdf (#8)


When I give
pdfViewPager.setScaleX(1.5f);
I finding that the ui is not looking good.
If is give pdfViewPager.setScaleY(1.5f);
I could see that some portion of pdf am not able to see. Is there any solution for the same ?

-

**Comment by voghDev** [comment] 2016-06-30 20:48
Hi again,

version *1.0.0* of the library has been released. You can now set a default scale to the PDFPagerAdapter, so every rendered page will have this scale applied.

There is a sample included in samples project, have a look at it and let me know if it suits your needs.

Thanks

**Closed** 2016-07-21 09:42 UTC
