### ISSUE TITLE
Two finger scroll on Samsung 8.x devices provoke IllegalArgumentException pointerIndex out of range

### ISSUE THREAD

**Issue by emitchel** [voghDev/PdfViewPager#123] opened 2019-05-06 21:09 UTC
On Samsung devices we've seen a particular issue around the view pager - it was determined multi finger touches cause this error

You see it in other libraries - most commonly the following, https://github.com/chrisbanes/PhotoView/issues/31

And their workaround fixes the issue, just thought I'd drop this here as it could be an easy fix to this library

**The Error**

```
IllegalArgumentException pointerIndex out of range
android.view.MotionEvent.nativeGetAxisValue (MotionEvent.java)
android.view.MotionEvent.getX (MotionEvent.java:2519)
androidx.viewpager.widget.ViewPager.onInterceptTouchEvent (ViewPager.java:2072)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2696)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:600)
com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1871)
android.app.Activity.dispatchTouchEvent (Activity.java:3384)
androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:69)
androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:69)
com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:562)
android.view.View.dispatchPointerEvent (View.java:12782)
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:5615)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:5410)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4903)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4956)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4922)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:5059)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4930)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:5116)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4903)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4956)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4922)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4930)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4903)
android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:7654)
android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:7594)
android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:7555)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:7765)
android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:185)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:325)
android.os.Looper.loop (Looper.java:142)
android.app.ActivityThread.main (ActivityThread.java:6938)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

**The workaround**

```
public class ViewPagerFixed extendsViewPager {

    public ViewPagerFixed(Context context) {
        super(context);
    }

    public ViewPagerFixed(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        try {
            return super.onTouchEvent(ev);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return false;
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            return super.onInterceptTouchEvent(ev);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return false;
    }
}
```

**Comment by voghDev** [comment] 2019-05-07 05:21
Hi,

this was related to PhotoView library. The newest version of the library is not using PhotoView anymore, so you can update to avoid this crash.

Anyway I'm closing this because it is a duplicate of issues #14 #19 #20 #21 #43 #71 #100 and #103. Please search for the error before opening a new issue

Thanks for using the lib ;-)

**Closed by voghDev** 2019-05-07 05:21 UTC

**Comment by emitchel** [comment] 2019-05-07 14:15
Crap - I always try to search and thought github issues search did so by title contains 
https://github.com/voghDev/PdfViewPager/issues?utf8=%E2%9C%93&q=is%3Aissue+pointer
https://github.com/voghDev/PdfViewPager/issues?utf8=%E2%9C%93&q=is%3Aissue+illegal+
https://github.com/voghDev/PdfViewPager/issues?utf8=%E2%9C%93&q=is%3Aissue+illegalargument

These searches bring up nothing -I swear these would have found the other issues with `illegalargumentexception` in the title before - maybe their search querying has changed on github. 

My bad!
